name: Publish

on:
  pull_request:
    branches: [master, next]
    types: [closed]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'release/') && github.event.pull_request.merged == true
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Use Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: 'Install Dependencies'
        run: npm ci --ignore-scripts
      - name: 'Publish'
        run: npm run publish:packages -- --tag latest
        if: github.base_ref == 'master'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: 'Prerelease Publish'
        run: npm run publish:packages -- --tag next
        if: github.base_ref == 'next'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
