name: Unit Tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: 
      - 'master'
      - 'next'
    paths-ignore:
      - 'docs/**'  

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        react: [16, 17, 18]
        include:
          - react: 16
            reactTestingLibrary: 12
          - react: 17
            reactTestingLibrary: 12
          - react: 18
            reactTestingLibrary: 14
            coverage: true
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Use Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm i react@${{ matrix.react }} react-dom@${{ matrix.react }} @testing-library/react@${{ matrix.reactTestingLibrary }}
      - run: npm test --coverage=${{ matrix.coverage || false }}
        env:
          CI: true
      - if: ${{ matrix.coverage }}
        name: Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
