name: Release

on:
  pull_request:
    branches: [master, next]
    types: [opened, reopened]

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'release/')
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.VERSIONING_TOKEN }}
      - name: Setup Git
        run: |
          git config --global user.email "ci@rmwc.io"
          git config --global user.name "RMWC CI"
      - name: Use Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - name: 'Patch Release'
        run: npm run -- release:patch
        if: contains(github.head_ref, '/patch') && github.base_ref == 'master'
      - name: 'Minor Release'
        run: npm run -- release:minor
        if: contains(github.head_ref, '/minor') && github.base_ref == 'master'
      - name: 'Major Release'
        run: npm run -- release:major
        if: contains(github.head_ref, '/major') && github.base_ref == 'master'
      - name: 'Aplpha Release'
        run: npm run -- release:alpha
        if: contains(github.head_ref, '/alpha') && github.base_ref == 'master'
      - name: 'Patch Prerelease'
        run: npm run -- prerelease:patch
        if: contains(github.head_ref, '/patch') && github.base_ref == 'next'
      - name: 'Minor Prerelease'
        run: npm run -- prerelease:minor
        if: contains(github.head_ref, '/minor') && github.base_ref == 'next'
      - name: 'Major Prerelease'
        run: npm run -- prerelease:major
        if: contains(github.head_ref, '/major') && github.base_ref == 'next'
      - name: 'Aplpha Prerelease'
        run: npm run -- prerelease:alpha
        if: contains(github.head_ref, '/alpha') && github.base_ref == 'next'
      - name: 'Push'
        run: git push --follow-tags
      - name: 'Build Docs'
        run: npm run build:docs
